# -*- coding: utf-8 -*-
"""data_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zbQHr-KxVp1802yMM_ba-ZZwnoe_Oi57
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Better plot style
sns.set(style="whitegrid")

import pandas as pd

# Read directly from Colab's file system
df = pd.read_excel('/content/X_scaled_processed.xlsx')  # Use your actual filename

# Show first rows
df.head()

plt.figure(figsize=(12,6))
plt.plot(df["timestamp_numeric"], df["CPU_Usage"], label="CPU Usage")
plt.plot(df["timestamp_numeric"], df["Bandwidth_Usage"], label="Bandwidth Usage")
plt.plot(df["timestamp_numeric"], df["Energy_Consumption"], label="Energy Consumption")

plt.xlabel("Time")
plt.ylabel("Usage / Consumption")
plt.title("System Behavior Over Time")
plt.legend()
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Between Features")
plt.show()

plt.figure(figsize=(7,5))
sns.scatterplot(
    x="CPU_Usage",
    y="Energy_Consumption",
    data=df
)
plt.title("CPU Usage vs Energy Consumption")
plt.show()

plt.figure(figsize=(7,5))
sns.scatterplot(
    x="Bandwidth_Usage",
    y="Energy_Consumption",
    data=df
)
plt.title("Bandwidth Usage vs Energy Consumption")
plt.show()

plt.figure(figsize=(10,5))
plt.plot(df["timestamp_numeric"], df["LSTM_Predicted_log"])
plt.yscale("log")
plt.xlabel("Time")
plt.ylabel("LSTM Predicted (log scale)")
plt.title("LSTM Prediction Over Time")
plt.show()

df[["CPU_Usage", "Bandwidth_Usage", "Energy_Consumption"]].hist(
    bins=10,
    figsize=(10,5)
)
plt.suptitle("Distribution of System Metrics")
plt.show()

!pip install plotly

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df["timestamp_numeric"],
    y=df["CPU_Usage"],
    mode="lines",
    name="CPU Usage"
))

fig.add_trace(go.Scatter(
    x=df["timestamp_numeric"],
    y=df["Bandwidth_Usage"],
    mode="lines",
    name="Bandwidth Usage"
))

fig.add_trace(go.Scatter(
    x=df["timestamp_numeric"],
    y=df["Energy_Consumption"],
    mode="lines",
    name="Energy Consumption"
))

fig.update_layout(
    title="Interactive System Resource Behavior Over Time",
    xaxis_title="Time",
    yaxis_title="Value",
    hovermode="x unified"
)

fig.show()

corr = df.corr()

fig = px.imshow(
    corr,
    text_auto=".2f",
    title="Interactive Correlation Heatmap",
    color_continuous_scale="RdBu_r"
)

fig.show()